### PR TITLE
Show update information on the about page

### PR DESCRIPTION
**Pull request by thedaniel**
Closes https://github.com/atom/about/issues/1

@simurai whipped up some static UI for this last week, and I started on wiring it up (with some foundational work in https://github.com/atom/atom/pull/10675 ) while I was first responder last week. Unfortunately I didn't get beyond a spike at that time, but here's what was in my working copy this morning :) I'm going to work on something else this week, but these are here for future core team members on bug rotation, community folks, or most likely me to pick up and finish in the hopefully near future. There are extensive mockups in a private design repo, but it's pretty self-explanatory if you look at what's in the UI that Simon added here.

### CODE REVIEW

**Comment by simurai** [comment]
We can post a screenshot here too:

update-0

update-on

Also, the "Automatically download updates" toggle could also be implemented in a second step/PR.

**Comment by mnquintana** [comment]
@thedaniel Does this mean that this depends on #10675 to work? Did you want to finish that up first? I was thinking of taking a look at this this week.

**Comment by thedaniel** [comment]
@mnquintana yep, it needs https://github.com/atom/atom/pull/10675 or something like it to work - I can finish that up but I'm working on another project for a few days first.

**Comment by joshaber** [comment]
@mnquintana If you wanna take this and https://github.com/atom/atom/pull/10675 on, they're all yours!

Let us know if you get stuck or don't have the time and we can pick them back up.

**Comment by kuychaco** [comment]
@simurai - Awesome job with this new UI, looks great!

One thing I noticed is that we may not be able to display the information as you have it for the case of Manual updates. 

Manual update | Info
--- | ---
update-b-3-small | 2. When "Automatically download updates" is turned off, updates need to be downloaded manually.  `Atom 1.4`

The current [autoUpdater Electron API](http://electron.atom.io/docs/v0.36.8/api/auto-updater/#event-update-available) is set up so that when you check for an update and there is one available the update is downloaded automatically. 

So it looks like for the Manual Update we won't be able to provide information about a newly available update prior to downloading the update. We could maybe specify when the last update was downloaded and have a button for checking/downloading any new ones, since the two go hand-in-hand (assuming that an update is available).

**Comment by thedaniel** [comment]
> So it looks like for the Manual Update we won't be able to provide information about a newly available update prior to downloading the update.

Not sure if it's outside of the scope of these changes, but you could get this information by hitting the mac & windows update endpoints directly and checking the version numbers.

**Comment by kuychaco** [comment]
Ah, good point. Thanks for pointing that out @thedaniel.

**Comment by simurai** [comment]
If "Manual Update" needs a lot of work, or some new APIs are needed, we could keep this PR to "Auto Update" only. Basically remove the checkbox from the UI. And then maybe add the "Manual Update" as a new feature later.

I think the main use case for "Manual Update" is when you're on the go and don't want Atom to eat into your (expensive) data plan or so. You probably could already block Atom with an app like https://www.tripmode.ch, so maybe not too urgent. I just remember that it came up in Discuss, I think.. /cc @lee-dohm

**Comment by lee-dohm** [comment]
Regarding reasons for not wanting to automatically update: https://github.com/atom/atom/issues/1882

**Comment by benogle** [comment]
As @kuychaco mentioned, there are a bunch of things defined in the designs that are not supported by electron / squirrel. Here's what it does:

When you are on a dev build or in linux you will see this:

unsupported

In the `idle` state, when there has been no update checked for, you will see this:

automatic

And if you uncheck the autoupdate box: 

manual

When it's checking for an update:

checking

And when it's downloading an update we dont have any information about the thing it's downloading. So all we get is this: 

downloading

Then if it's up to date: 

up-to-date

And if there is a new version that can be installed. You will see this:

restart

TODO: 

* [ ] Fix lint errors in specs
* [ ] Make sure my assumptions for version information coming back from electron on downloaded are correct

**Comment by simurai** [comment]
> In the `idle` state, when there has been no update checked for,

Would it be too much to automatically "Check for update" every time you open the About page? Then there wouldn't be an `idle` state. After checking it's either "up to date", "starts downloading" or "update available for manual download".

**Comment by Stanzilla** [comment]
Note: Restart to install still does not work on Windows (see https://github.com/atom/atom/issues/6612#issuecomment-187576294)

**Comment by benogle** [comment]
> Would it be too much to automatically "Check for update" every time you open the About page?

Nope. Added that when auto updates are turned on. For manual updates, they will still need to manually click the button.

**Comment by mnquintana** [comment]
[One idea I had for this flow](https://github.com/atom/about/issues/1#issue-89798110) that would be awesome to see added would be to:

- Check for newer commits on `master` if using a dev build of Atom, and notify the user that they're behind (and how far they are behind?)
- Check for newer releases on Linux and link to the appropriate download (until we have proper auto-update support on Linux)

**Comment by benogle** [comment]
> One idea I had for this flow 

Definitely would be cool to add those things at some point. For now, I really want to get this out and working. The current squirrel icon pointing to the atom.io release notes page is pretty confusing, and this should be a big help.

I think this is ready. When https://github.com/atom/atom/pull/10675 is merged, this can be as well.

**Comment by YuriSolovyov** [comment]
@benogle 
> When you are on a dev build or in linux you will see no update UI

It would be awesome if on linux it still checked for updates, and provided the link to Github releases page if there is one.

**Comment by benogle** [comment]
> It would be awesome if on linux it still checked for updates, and provided the link to Github releases page if there is one.

Definitely could be an addition to this, but is not on our radar at the moment.

**Comment by YuriSolovyov** [comment]
Should I file a bug?

**Pull request merged**
